/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithLayoutRouteImport } from './routes/_withLayout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as WithLayoutIndexRouteImport } from './routes/_withLayout/index'
import { Route as WithLayoutUsersRouteImport } from './routes/_withLayout/users'
import { Route as WithLayoutTransactionsRouteImport } from './routes/_withLayout/transactions'
import { Route as WithLayoutBooksRouteImport } from './routes/_withLayout/books'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as WithLayoutBookRequestsIndexRouteImport } from './routes/_withLayout/book-requests/index'

const WithLayoutRoute = WithLayoutRouteImport.update({
  id: '/_withLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WithLayoutIndexRoute = WithLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithLayoutRoute,
} as any)
const WithLayoutUsersRoute = WithLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => WithLayoutRoute,
} as any)
const WithLayoutTransactionsRoute = WithLayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => WithLayoutRoute,
} as any)
const WithLayoutBooksRoute = WithLayoutBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => WithLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const WithLayoutBookRequestsIndexRoute =
  WithLayoutBookRequestsIndexRouteImport.update({
    id: '/book-requests/',
    path: '/book-requests/',
    getParentRoute: () => WithLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WithLayoutIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/books': typeof WithLayoutBooksRoute
  '/transactions': typeof WithLayoutTransactionsRoute
  '/users': typeof WithLayoutUsersRoute
  '/book-requests/': typeof WithLayoutBookRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WithLayoutIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/books': typeof WithLayoutBooksRoute
  '/transactions': typeof WithLayoutTransactionsRoute
  '/users': typeof WithLayoutUsersRoute
  '/book-requests': typeof WithLayoutBookRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_withLayout': typeof WithLayoutRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_withLayout/books': typeof WithLayoutBooksRoute
  '/_withLayout/transactions': typeof WithLayoutTransactionsRoute
  '/_withLayout/users': typeof WithLayoutUsersRoute
  '/_withLayout/': typeof WithLayoutIndexRoute
  '/_withLayout/book-requests/': typeof WithLayoutBookRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/books'
    | '/transactions'
    | '/users'
    | '/book-requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/books'
    | '/transactions'
    | '/users'
    | '/book-requests'
  id:
    | '__root__'
    | '/_auth'
    | '/_withLayout'
    | '/_auth/sign-in'
    | '/_withLayout/books'
    | '/_withLayout/transactions'
    | '/_withLayout/users'
    | '/_withLayout/'
    | '/_withLayout/book-requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  WithLayoutRoute: typeof WithLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_withLayout': {
      id: '/_withLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_withLayout/': {
      id: '/_withLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithLayoutIndexRouteImport
      parentRoute: typeof WithLayoutRoute
    }
    '/_withLayout/users': {
      id: '/_withLayout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof WithLayoutUsersRouteImport
      parentRoute: typeof WithLayoutRoute
    }
    '/_withLayout/transactions': {
      id: '/_withLayout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof WithLayoutTransactionsRouteImport
      parentRoute: typeof WithLayoutRoute
    }
    '/_withLayout/books': {
      id: '/_withLayout/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof WithLayoutBooksRouteImport
      parentRoute: typeof WithLayoutRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_withLayout/book-requests/': {
      id: '/_withLayout/book-requests/'
      path: '/book-requests'
      fullPath: '/book-requests/'
      preLoaderRoute: typeof WithLayoutBookRequestsIndexRouteImport
      parentRoute: typeof WithLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface WithLayoutRouteChildren {
  WithLayoutBooksRoute: typeof WithLayoutBooksRoute
  WithLayoutTransactionsRoute: typeof WithLayoutTransactionsRoute
  WithLayoutUsersRoute: typeof WithLayoutUsersRoute
  WithLayoutIndexRoute: typeof WithLayoutIndexRoute
  WithLayoutBookRequestsIndexRoute: typeof WithLayoutBookRequestsIndexRoute
}

const WithLayoutRouteChildren: WithLayoutRouteChildren = {
  WithLayoutBooksRoute: WithLayoutBooksRoute,
  WithLayoutTransactionsRoute: WithLayoutTransactionsRoute,
  WithLayoutUsersRoute: WithLayoutUsersRoute,
  WithLayoutIndexRoute: WithLayoutIndexRoute,
  WithLayoutBookRequestsIndexRoute: WithLayoutBookRequestsIndexRoute,
}

const WithLayoutRouteWithChildren = WithLayoutRoute._addFileChildren(
  WithLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  WithLayoutRoute: WithLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
